@extends("welcome")

@section("content")

    <div class="container bg-light" style="margin-top: 100px">

        <div class="row">
            <div class="col-md-10 mx-auto">
                <div class="card" style="border: none;">
                    <div class="card-body text-justify" style="line-height: 30px !important;">
                        <h2>Privacy Policy</h2>
                        <strong class="d-block">Last updated: January 3, 2023</strong>
                        This Privacy Policy describes our policies and procedures on the collection, use and disclosure
                        of your information when you use the service and tells you about your privacy rights and how the
                        law protects you.
                        We use your personal data to provide and improve the service. By using the service, you agree to
                        the collection and use of information in accordance with this Privacy Policy.
                        <h3>Interpretation and Definitions</h3>
                        <h4>Interpretation</h4>
                        The words of which the initial letter is capitalized have meanings defined under the following
                        conditions. The following definitions shall have the same meaning regardless of whether they
                        appear in singular or in plural.
                        <h4>Definitions</h4>

                        <strong class="d-block"> For the purposes of this Privacy Policy:</strong>
                        <span>
                            <div class="row">
                                <div class="col-md-1">

                                </div>
                                <div class="col-md-11">


                                    <strong>Account</strong> means a unique account created for you to access our service or parts of our service.<br>
                                    <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where <strong>"control"</strong> means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</br>
                                    <strong>Application</strong> means the software program provided by the Company downloaded by you on any electronic device, named nuna<br>
                                    <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Nuna Technologies Limited.<br>
                                    <strong>Country</strong> refers to: Ghana<br>
                                    <strong>Device</strong> means any device that can access the service such as a computer, a cell phone or a digital tablet.<br>
                                    <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.<br>
                                    <strong>Service</strong> refers to the Application.<br>
                                    <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the service, to provide the service on behalf of the Company, to perform services related to the service or to assist the Company in analyzing how the service is used.<br>
                                    <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the service or from the service infrastructure itself (for example, the duration of a page visit).<br>
                                    <strong>You</strong> means the individual accessing or using the service, or the company, or other legal entity on behalf of which such individual is accessing or using the service, as applicable.<br>
                          </div>
                            </div>
                       </span>
                        <h2>Collecting and Using your personal Data</h2>
                        <h4>Types of Data Collected</h4>
                        <strong class="d-block">Personal Data</strong>
                        While using our service, we may ask you to provide us with certain personally identifiable
                        information that can be used to contact or identify you. personally identifiable information may
                        include, but is not limited to:
                        <ul style="list-style: circle !important; margin-left: 40px; padding: 20px">
                            <li>Email address</li>
                            <li>First name and last name</li>
                            <li>Phone number</li>
                            <li>Usage Data</li>
                        </ul>


                        <strong class="d-block"> Usage Data</strong>
                        <p>Usage Data is collected automatically when using the service.</p>

                        <p>
                            Usage Data may include information such as your Device's Internet Protocol address (e.g. IP
                            address), browser type, browser version, the pages of our service that you visit, the time
                            and date of your visit, the time spent on those pages, unique device identifiers and other
                            diagnostic data.
                        </p>
                        <p>
                            When you access the service by or through a mobile device, We may collect certain
                            information automatically, including, but not limited to, the type of mobile device you use,
                            your mobile device unique ID, the IP address of your mobile device, your mobile operating
                            system, the type of mobile Internet browser you use, unique device identifiers and other
                            diagnostic data.
                        </p>
                        <p>


                            We may also collect information that your browser sends whenever you visit our service or
                            when you access the service by or through a mobile device.</p>
                        <strong class="d-block"> Information Collected while Using the Application</strong>

                        While using Our Application, in order to provide features of Our Application, We may collect,
                        with your prior permission:
                        <ul style="list-style: circle !important; margin-left: 40px; padding: 20px">
                            <li>Information regarding your location</li>
                            <li>Information from your Device's phone book (contacts list)</li>
                            <li>Pictures and other information from your Device's camera and photo library</li>
                        </ul>

                        <p>


                        We use this information to provide features of Our service, to improve and customize Our
                        service. The information may be uploaded to the Company's servers and/or a service Provider's
                        server or it may be simply stored on your device.
                        </p>

                        <p>You can enable or disable access to this information at any time, through your Device settings.</p>

                        <strong class="d-block">Use of your personal Data</strong>
                        <span>
                            <div class="row">
                                <div class="col-md-1">

                                </div>
                                <div class="col-md-11">


                        The Company may use personal Data for the following purposes:

                                    <strong>To provide and maintain our service</strong>, including to monitor the usage of our service.</br>
                                    <strong>To manage your Account:</strong> to manage your registration as a user of the service. The personal Data
                        you provide can give you access to different functionalities of the service that are available
                        to you as a registered user.<br>

                                    <strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase
                        contract for the products, items or services you have purchased or of any other contract with Us
                        through the service.<br>
                                    <strong>To contact you:</strong> To contact you by email, telephone calls, SMS, or other equivalent forms of
                        electronic communication, such as a mobile application's push notifications regarding updates or
                        informative communications related to the functionalities, products or contracted services,
                        including the security updates, when necessary or reasonable for their implementation.<br>
                                    <strong>To provide you</strong> with news, special offers and general information about other goods, services and
                        events which we offer that are similar to those that you have already purchased or enquired
                        about unless you have opted not to receive such information.</br>
                                    <strong>To manage your requests:</strong> To attend and manage your requests to Us.
                        For other purposes: We may use your information for other purposes, such as data analysis,
                        identifying usage trends, determining the effectiveness of our promotional campaigns and to
                        evaluate and improve our service, products, services, marketing and your experience.
                                </div>
                            </div>
                        </span>
                        We may share your personal information in the following situations:<br>

                        <strong>• With service Providers:</strong> We may share your personal information with service Providers to
                        monitor and analyze the use of our service, to contact you.<br>
                        <strong>• For business transfers:</strong> We may share or transfer your personal information in connection with,
                        or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all
                        or a portion of Our business to another company.<br>
                        <strong>• With Affiliates:</strong> We may share your information with Our affiliates, in which case we will
                        require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and
                        any other subsidiaries, joint venture partners or other companies that We control or that are
                        under common control with Us.<br>
                        <strong>• With business partners:</strong> We may share your information with Our business partners to offer you
                        certain products, services or promotions.
                        <strong>• With other users:</strong> when you share personal information or otherwise interact in the public
                        areas with other users, such information may be viewed by all users and may be publicly
                        distributed outside.<br>
                        <strong>• With your consent:</strong> We may disclose your personal information for any other purpose with your
                        consent.<br>

                        <strong class="d-block">Retention of your personal Data</strong>

                        The Company will retain your personal Data only for as long as is necessary for the purposes set
                        out in this Privacy Policy. We will retain and use your personal Data to the extent necessary to
                        comply with our legal obligations (for example, if we are required to retain your data to comply
                        with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                        The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally
                        retained for a shorter period of time, except when this data is used to strengthen the security
                        or to improve the functionality of Our service, or We are legally obligated to retain this data
                        for longer time periods.
                        <strong class="d-block">Transfer of your personal Data</strong>
                        Your information, including personal Data, is processed at the Company's operating offices and
                        in any other places where the parties involved in the processing are located. It means that this
                        information may be transferred to — and maintained on — computers located outside of your state,
                        province, country or other governmental jurisdiction where the data protection laws may differ
                        from those from your jurisdiction.
                        Your consent to this Privacy Policy followed by your submission of such information represents
                        your agreement to that transfer.
                        The Company will take all steps reasonably necessary to ensure that your data is treated
                        securely and in accordance with this Privacy Policy and no transfer of your personal Data will
                        take place to an organization or a country unless there are adequate controls in place including
                        the security of your data and other personal information.
                        <strong class="d-block">Delete your personal Data</strong>
                        You have the right to delete or request that We assist in deleting the personal Data that We
                        have collected about you.
                        Our service may give you the ability to delete certain information about you from within the
                        service.
                        You may update, amend, or delete your information at any time by signing in to your Account, if
                        you have one, and visiting the account settings section that allows you to manage your personal
                        information. you may also contact Us to request access to, correct, or delete any personal
                        information that you have provided to Us.
                        Please note, however, that We may need to retain certain information when we have a legal
                        obligation or lawful basis to do so.
                        <h4>Disclosure of your personal Data</h4>
                        <strong class="d-block">Business Transactions</strong>
                        If the Company is involved in a merger, acquisition or asset sale, your personal Data may be
                        transferred. We will provide notice before your personal Data is transferred and becomes subject
                        to a different Privacy Policy.
                        <strong class="d-block">Law enforcement</strong>
                        Under certain circumstances, the Company may be required to disclose your personal Data if
                        required to do so by law or in response to valid requests by public authorities (e.g. a court or
                        a government agency).
                        <strong class="d-block">Other legal requirements</strong>
                        The Company may disclose your personal Data in the good faith belief that such action is
                        necessary to:
                        <ul>

                            <li>• Comply with a legal obligation</li>
                            <li>• Protect and defend the rights or property of the Company</li>
                            <li>• Prevent or investigate possible wrongdoing in connection with the service</li>
                            <li>• Protect the personal safety of Users of the service or the public</li>
                            <li>• Protect against legal liability</li>
                        </ul>

                        <h4>Security of your personal Data</h4>

                        The security of your personal Data is important to Us, but remember that no method of
                        transmission over the Internet, or method of electronic storage is 100% secure. While We strive
                        to use commercially acceptable means to protect your personal Data, We cannot guarantee its
                        absolute security.
                        <h2>Children's Privacy</h2>
                        Our service does not address anyone under the age of 13. We do not knowingly collect personally
                        identifiable information from anyone under the age of 13. If you are a parent or guardian and
                        you are aware that your child has provided Us with personal Data, please contact Us. If We
                        become aware that We have collected personal Data from anyone under the age of 13 without
                        verification of parental consent, We take steps to remove that information from Our servers.
                        If We need to rely on consent as a legal basis for processing your information and your country
                        requires consent from a parent, We may require your parent's consent before We collect and use
                        that information.
                        <h2>Links to Other Websites</h2>
                        Our service may contain links to other websites that are not operated by Us. If you click on a
                        third party link, you will be directed to that third party's site. We strongly advise you to
                        review the Privacy Policy of every site you visit.
                        We have no control over and assume no responsibility for the content, privacy policies or
                        practices of any third party sites or services.
                        <h2>Changes to this Privacy Policy</h2>
                        We may update Our Privacy Policy from time to time. We will notify you of any changes by posting
                        the new Privacy Policy on this page.
                        We will let you know via email and/or a prominent notice on Our service, prior to the change
                        becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                        you are advised to review this Privacy Policy periodically for any changes. Changes to this
                        Privacy Policy are effective when they are posted on this page.
                       <h2>Contact Us</h2>
                        If you have any questions about this Privacy Policy, you can contact us:<br>
                        <strong>By email:</strong> help@mynunaa.com<br>
                        By visiting this page on our website:<a href="https://mynunaa.com" class="text-primary">https://mynunaa.com</a>

                    </div>
                </div>
            </div>
        </div>


    </div>



@endsection
